"""Increase shot_time length limit of journeycard to 20

Revision ID: 1de73b785299
Revises: 7cb7ed90d544
Create Date: 2025-04-21 15:53:16.176592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1de73b785299'
down_revision = '7cb7ed90d544'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('journey_card', schema=None) as batch_op:
        batch_op.alter_column('shot_time',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('journey_card', schema=None) as batch_op:
        batch_op.alter_column('shot_time',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)

    # ### end Alembic commands ###
