"""Initial database schema

Revision ID: 7cb7ed90d544
Revises: 
Create Date: 2025-04-16 02:12:32.771297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cb7ed90d544'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('image_file', sa.String(length=20), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('coffee_journey',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('drink', sa.String(length=100), nullable=False),
    sa.Column('coffee_beans', sa.String(length=100), nullable=False),
    sa.Column('brewing_device', sa.String(length=100), nullable=False),
    sa.Column('grinder', sa.String(length=100), nullable=False),
    sa.Column('grind_setting', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('iteration', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('coffee_setup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('drink', sa.String(length=100), nullable=False),
    sa.Column('coffee_beans', sa.String(length=100), nullable=False),
    sa.Column('brewing_device', sa.String(length=100), nullable=False),
    sa.Column('grinder', sa.String(length=100), nullable=False),
    sa.Column('grind_setting', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('date_posted', sa.DateTime(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('journey_card',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grind_setting', sa.String(length=100), nullable=False),
    sa.Column('iteration', sa.Integer(), nullable=False),
    sa.Column('date_posted', sa.DateTime(), nullable=False),
    sa.Column('journey_id', sa.Integer(), nullable=False),
    sa.Column('shot_time', sa.String(length=10), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['journey_id'], ['coffee_journey.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('journey_card')
    op.drop_table('post')
    op.drop_table('coffee_setup')
    op.drop_table('coffee_journey')
    op.drop_table('user')
    # ### end Alembic commands ###
