"""added grind_amount

Revision ID: fc8905e1d12f
Revises: 1de73b785299
Create Date: 2025-04-30 18:06:59.654148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc8905e1d12f'
down_revision = '1de73b785299'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('journey_card', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grind_amount', sa.String(length=40), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('journey_card', schema=None) as batch_op:
        batch_op.drop_column('grind_amount')

    # ### end Alembic commands ###
